spring:
  datasource:
    url: jdbc:h2:mem:tokendb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 3000

logger:
  level:
    root: INFO
    com.zianpayne.tokenization: DEBUG